import Link from 'next/link';

export const metadata = {
  title: 'Terms of Service — Health Saviors',
  description: 'The terms that govern your use of Health Saviors.',
};

const SECTIONS: { h: string; body: React.ReactNode }[] = [
  {
    h: '1. Acceptance',
    body: <p>By creating an account or using Health Saviors (the "Service") you agree to these Terms and to our <Link href="/privacy" className="text-accent underline">Privacy Policy</Link>. If you do not agree, do not use the Service.</p>,
  },
  {
    h: '2. Not medical advice',
    body: (
      <>
        <p className="mb-2"><strong>The Service is not a medical device, doctor, or substitute for professional medical care.</strong></p>
        <p>The AI agents (Nurse, Gatekeeper, Nutritionist, MindCare) provide general wellness and educational information only. Their output is generated by large language models and may be incomplete, outdated, or wrong. Never rely on the Service for diagnosis, prescription, or emergency care.</p>
        <p className="mt-2">If you experience an emergency call your local emergency number (e.g. <strong>911</strong> in the US, <strong>119</strong> in Korea), the <strong>988</strong> Suicide &amp; Crisis Lifeline (US), or visit the nearest emergency department.</p>
      </>
    ),
  },
  {
    h: '3. Eligibility',
    body: <p>You must be 16 or older. By using the Service you represent that this is true and that you have the legal capacity to enter these Terms.</p>,
  },
  {
    h: '4. Your account',
    body: (
      <ul className="list-disc ml-5 space-y-1">
        <li>You authenticate by signing a message with your wallet. You are responsible for protecting access to that wallet and to your device.</li>
        <li>You agree not to impersonate others, log false data to game rewards, or use the Service to harass other users.</li>
        <li>We may suspend or terminate accounts that violate these Terms, attempt to attack the Service, or abuse the AI features.</li>
      </ul>
    ),
  },
  {
    h: '5. Your content',
    body: (
      <ul className="list-disc ml-5 space-y-1">
        <li>You retain ownership of the content you create (community posts, photos, logs).</li>
        <li>By posting to the community feed you grant Health Saviors a non-exclusive license to display that content within the Service.</li>
        <li>You agree not to upload content that is illegal, defamatory, hateful, sexually explicit, or that infringes anyone else's rights.</li>
        <li>We may remove content or accounts that violate the above without notice.</li>
      </ul>
    ),
  },
  {
    h: '6. Rewards (H2E)',
    body: (
      <p>
        H2E points are an in-app metric used to reflect activity streaks. They have no guaranteed monetary value, are not redeemable for cash by default, and may be reset, paused, or modified to maintain fairness or comply with regulation.
      </p>
    ),
  },
  {
    h: '7. Push notifications',
    body: <p>If you enable push notifications you agree to receive them at the categories you have selected in <Link href="/notifications" className="text-accent underline">/notifications</Link>. You can revoke this at any time from the same screen or in your browser/OS settings.</p>,
  },
  {
    h: '8. Service "as is"',
    body: <p>The Service is provided <strong>as-is</strong>, without warranty of any kind. We do not guarantee uninterrupted availability, accuracy of AI output, or fitness for any particular purpose. To the fullest extent permitted by law, our liability is limited to the amount you have paid us in the previous 12 months (which may be zero).</p>,
  },
  {
    h: '9. Indemnity',
    body: <p>You agree to indemnify Health Saviors against any third-party claim arising from content you posted or actions you took on the Service in violation of these Terms.</p>,
  },
  {
    h: '10. Changes',
    body: <p>We may update these Terms. Material changes will be surfaced in-app. Continued use after a change means you accept the new Terms.</p>,
  },
  {
    h: '11. Contact',
    body: <p>Questions: <a href="mailto:admin@health-saviors.app" className="text-accent underline">admin@health-saviors.app</a></p>,
  },
];

export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 pt-2 pb-16">
      <h1 className="font-display text-3xl sm:text-4xl text-text-primary">Terms of Service</h1>
      <p className="text-sm text-text-muted mt-2">Last updated: 2026-05-15</p>

      <div className="mt-8 space-y-6 text-sm text-text-secondary leading-relaxed">
        {SECTIONS.map(s => (
          <section key={s.h}>
            <h2 className="text-base font-semibold text-text-primary mb-2">{s.h}</h2>
            {s.body}
          </section>
        ))}

        <div className="pt-4 mt-8 border-t border-border-subtle text-xs text-text-muted">
          See also: <Link href="/privacy" className="text-accent underline">Privacy Policy</Link>.
        </div>
      </div>
    </div>
  );
}
